import fs from 'fs';
import path from 'path';

// Generate a valid PNG file for PWA icons
// We can use a 1x1 green/gold PNG or standard 192px/512px PNG buffer
const createSimplePng = () => {
  // Base64 of a valid 192x192 green-gold logo PNG
  const svgIcon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
    <rect width="512" height="512" rx="100" fill="#064e3b"/>
    <circle cx="256" cy="256" r="210" fill="none" stroke="#fbbf24" stroke-width="12"/>
    <circle cx="256" cy="256" r="180" fill="#047857"/>
    <text x="256" y="270" font-size="160" font-family="sans-serif" font-weight="900" fill="#fbbf24" text-anchor="middle" dominant-baseline="middle">TGS</text>
    <text x="256" y="370" font-size="36" font-family="sans-serif" font-weight="bold" fill="#ffffff" text-anchor="middle">TRUST GROWTH</text>
  </svg>`;

  const publicDir = path.join(process.cwd(), 'public');
  fs.writeFileSync(path.join(publicDir, 'icon.svg'), svgIcon);
  fs.writeFileSync(path.join(publicDir, 'icon-192.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAIAAADdvvtQAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE0SURBVHhe7cExAQAAAMKg9U9tCj+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgDkDTmUAAeZlhg4AAAAASUVORK5CYII=', 'base64'));
  fs.writeFileSync(path.join(publicDir, 'icon-512.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAAAAAD6WwMPAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE8SURBVHhe7cExAQAAAMKg9U9tDB+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwJsBqYcAAad4+54AAAAASUVORK5CYII=', 'base64'));
};

createSimplePng();
console.log("PWA Icons generated.");
